// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/about.tsx";
import * as $2 from "./routes/api/like.ts";
import * as $3 from "./routes/api/login.ts";
import * as $4 from "./routes/api/logout.ts";
import * as $5 from "./routes/api/post.ts";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/post.tsx";
import * as $8 from "./routes/posts.tsx";
import * as $$0 from "./islands/NewPost.tsx";
import * as $$1 from "./islands/OldPost.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/about.tsx": $1,
    "./routes/api/like.ts": $2,
    "./routes/api/login.ts": $3,
    "./routes/api/logout.ts": $4,
    "./routes/api/post.ts": $5,
    "./routes/index.tsx": $6,
    "./routes/post.tsx": $7,
    "./routes/posts.tsx": $8,
  },
  islands: {
    "./islands/NewPost.tsx": $$0,
    "./islands/OldPost.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
